// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationsPetDemo.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MigrationsPetDemo.Storage.Migrations
{
    [DbContext(typeof(VetDbContext))]
    [Migration("20260327112314_AddVet")]
    partial class AddVet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Pets")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MigrationsPetDemo.Model.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Notes", "Pets");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Owner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Owners", "Pets");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets", "Pets");

                    b.HasDiscriminator().HasValue("Pet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vets", "Pets");
                });

            modelBuilder.Entity("PetVet", b =>
                {
                    b.Property<long>("PetsId")
                        .HasColumnType("bigint");

                    b.Property<int>("VetsId")
                        .HasColumnType("integer");

                    b.HasKey("PetsId", "VetsId");

                    b.HasIndex("VetsId");

                    b.ToTable("PetVet", "Pets");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Hedgehog", b =>
                {
                    b.HasBaseType("MigrationsPetDemo.Model.Pet");

                    b.Property<bool>("IsDomesticatedBreed")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Hedgehog");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Horse", b =>
                {
                    b.HasBaseType("MigrationsPetDemo.Model.Pet");

                    b.Property<int>("ShoeSizeBack")
                        .HasColumnType("integer");

                    b.Property<int>("ShoeSizeFront")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Horse");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Note", b =>
                {
                    b.HasOne("MigrationsPetDemo.Model.Pet", "Pet")
                        .WithMany("Notes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Pet", b =>
                {
                    b.HasOne("MigrationsPetDemo.Model.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetVet", b =>
                {
                    b.HasOne("MigrationsPetDemo.Model.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigrationsPetDemo.Model.Vet", null)
                        .WithMany()
                        .HasForeignKey("VetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("MigrationsPetDemo.Model.Pet", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
